### PR TITLE
Jack

### PR DESCRIPTION
**Pull request by jackwax**
Added light baking 420

### CODE REVIEW

**Comment by Reapeth** [comment]
Looks a bit bright.

**Comment by jackwax** [comment]
AYE BOYS CHECK out my SICK LIGHTING

**Comment by Raj-Basu** [comment]
Liiiit

**Comment by jackwax** [comment]
ayyyy

**Comment by beckettm** [comment]
I don't do drugs

**Comment by jackwax** [comment]
:'(

**Pull request merged**
